# fly.toml app configuration file generated for fullstackopen-part3-falling-bird-1781 on 2025-02-10T11:48:01-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fullstackopen-part3-falling-bird-1781'
primary_region = 'sea'

[build]

[env]
  PORT = "3000" # fly.io forwards requests from port 80 to this port

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
